version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.railway.internal:5432/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=WTddBGggkVWcRooshuHpKxYaMBuFoBaU
      - PGDATABASE=railway
      - PGHOST=postgres.railway.internal
      - PGPASSWORD=WTddBGggkVWcRooshuHpKxYaMBuFoBaU
      - PGPORT=5432
      - PGUSER=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=WTddBGggkVWcRooshuHpKxYaMBuFoBaU
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data: 